/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Config: typeof import('./src/components/Config.vue')['default']
    FloatingPlayer: typeof import('./src/components/FloatingPlayer.vue')['default']
    ImageCarousel: typeof import('./src/components/ImageCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
