name: Auto-Merge Dependabot PRs
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - nyan-react # Set this to the default branch of your repository
      
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions: write-all

  
jobs:
   dependabot:
    name: 'Dependabot'
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}} # Detect that the PR author is dependabot
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
